"""Structured reason codes for execution decisions.

Use these constants whenever a trading decision is logged or a buy/sell
candidate is rejected. Stable strings so dashboard counters and tests can
group on them.
"""

from __future__ import annotations

from typing import Final


# --- Risk / market gates -----------------------------------------------------
MARKET_CLOSED: Final[str] = "MARKET_CLOSED"
KILL_SWITCH: Final[str] = "KILL_SWITCH"
NOTIONAL_TOO_SMALL: Final[str] = "NOTIONAL_TOO_SMALL"
MAX_POSITIONS: Final[str] = "MAX_POSITIONS"
MAX_SINGLE_ASSET: Final[str] = "MAX_SINGLE_ASSET"
MAX_DEPLOYED: Final[str] = "MAX_DEPLOYED"
SPREAD_TOO_WIDE: Final[str] = "SPREAD_TOO_WIDE"
NO_PRICE: Final[str] = "NO_PRICE"
NO_BROKER_QTY: Final[str] = "NO_BROKER_QTY"
PDT_PROTECTION: Final[str] = "PDT_PROTECTION"
LOCAL_POSITION_STALE: Final[str] = "LOCAL_POSITION_STALE"
LOCAL_POSITION_GHOST_QUARANTINED: Final[str] = "LOCAL_POSITION_GHOST_QUARANTINED"
LOCAL_POSITION_GHOST_CLEANED: Final[str] = "LOCAL_POSITION_GHOST_CLEANED"
LOCAL_LEDGER_NEGATIVE_QTY: Final[str] = "LOCAL_LEDGER_NEGATIVE_QTY"
SYNTHETIC_ROW_EXCLUDED_FROM_AUDIT: Final[str] = "SYNTHETIC_ROW_EXCLUDED_FROM_AUDIT"
BROKER_LOCAL_RECONCILED: Final[str] = "BROKER_LOCAL_RECONCILED"
BROKER_POSITION_UNTRACKED: Final[str] = "BROKER_POSITION_UNTRACKED"
WORKER_DOWNTIME_RECOVERY_STARTED: Final[str] = "WORKER_DOWNTIME_RECOVERY_STARTED"
STARTUP_DRAWDOWN_RECOVERY_STARTED: Final[str] = "STARTUP_DRAWDOWN_RECOVERY_STARTED"
DAILY_DRAWDOWN_KILL_SWITCH: Final[str] = "DAILY_DRAWDOWN_KILL_SWITCH"
ENTRY_PRICE_SOURCE_MISMATCH: Final[str] = "ENTRY_PRICE_SOURCE_MISMATCH"
EXIT_PRICE_POSITION_PRICE_MISMATCH: Final[str] = "EXIT_PRICE_POSITION_PRICE_MISMATCH"
SYMBOL_NOT_TRADEABLE: Final[str] = "SYMBOL_NOT_TRADEABLE"
NOT_FRACTIONABLE: Final[str] = "NOT_FRACTIONABLE"
INSUFFICIENT_BUYING_POWER: Final[str] = "INSUFFICIENT_BUYING_POWER"
STOCK_BUYS_DISABLED_INSUFFICIENT_BUYING_POWER: Final[str] = "STOCK_BUYS_DISABLED_INSUFFICIENT_BUYING_POWER"
CRYPTO_BUYS_DISABLED_INSUFFICIENT_BUYING_POWER: Final[str] = "CRYPTO_BUYS_DISABLED_INSUFFICIENT_BUYING_POWER"
CRYPTO_BUY_BLOCKED_POSITION_CAP_BELOW_MIN_NOTIONAL: Final[str] = (
    "CRYPTO_BUY_BLOCKED_POSITION_CAP_BELOW_MIN_NOTIONAL"
)
BROKER_RECONCILE_ADJUST: Final[str] = "BROKER_RECONCILE_ADJUST"
BROKER_LOCAL_MISMATCH: Final[str] = "BROKER_LOCAL_MISMATCH"
EXIT_BLOCKED_MARKET_CLOSED: Final[str] = "EXIT_BLOCKED_MARKET_CLOSED"
COOLDOWN: Final[str] = "COOLDOWN"
DAILY_LOSS_LIMIT: Final[str] = "DAILY_LOSS_LIMIT"
ALREADY_LONG: Final[str] = "ALREADY_LONG"
ALREADY_SHORT: Final[str] = "ALREADY_SHORT"

# --- Scalper specific --------------------------------------------------------
SCALP_EDGE_TOO_SMALL: Final[str] = "SCALP_EDGE_TOO_SMALL"
SCALP_SCORE_TOO_LOW: Final[str] = "SCALP_SCORE_TOO_LOW"
SCALP_NOT_ENABLED: Final[str] = "SCALP_NOT_ENABLED"

# --- Order outcomes ----------------------------------------------------------
PAPER_FILL: Final[str] = "PAPER_FILL"
ALPACA_ORDER_SUBMITTED: Final[str] = "ALPACA_ORDER_SUBMITTED"
ALPACA_ORDER_REJECTED: Final[str] = "ALPACA_ORDER_REJECTED"
ALPACA_PAPER_ORDER_SUBMITTED: Final[str] = "ALPACA_PAPER_ORDER_SUBMITTED"
ALPACA_PAPER_ORDER_REJECTED: Final[str] = "ALPACA_PAPER_ORDER_REJECTED"
LIVE_ORDER_BLOCKED: Final[str] = "LIVE_ORDER_BLOCKED"
SHADOW_LIVE_BLOCKED: Final[str] = LIVE_ORDER_BLOCKED

# --- Exit reasons ------------------------------------------------------------
STOP_LOSS: Final[str] = "STOP_LOSS"
TAKE_PROFIT: Final[str] = "TAKE_PROFIT"
TRAILING_STOP: Final[str] = "TRAILING_STOP"
MAX_HOLD: Final[str] = "MAX_HOLD"
EMERGENCY_EXIT: Final[str] = "EMERGENCY_EXIT"

# --- Deferred PDT exits (paper worker) ---------------------------------------
PDT_DEFERRED_EXIT_CREATED: Final[str] = "PDT_DEFERRED_EXIT_CREATED"
PDT_DEFERRED_EXIT_READY: Final[str] = "PDT_DEFERRED_EXIT_READY"
PDT_DEFERRED_EXIT_SUBMITTED: Final[str] = "PDT_DEFERRED_EXIT_SUBMITTED"
PDT_DEFERRED_EXIT_BLOCKED_AGAIN: Final[str] = "PDT_DEFERRED_EXIT_BLOCKED_AGAIN"
PDT_DEFERRED_EXIT_CANCELLED_NO_POSITION: Final[str] = "PDT_DEFERRED_EXIT_CANCELLED_NO_POSITION"
PDT_DEFERRED_EXIT_CANCELLED_PROFIT_REVERSED: Final[str] = "PDT_DEFERRED_EXIT_CANCELLED_PROFIT_REVERSED"

# --- Manual dashboard sells (paper; tagged manual_ui) ------------------------
MANUAL_SELL_SUBMITTED: Final[str] = "MANUAL_SELL_SUBMITTED"
MANUAL_SELL_BLOCKED_PDT: Final[str] = "MANUAL_SELL_BLOCKED_PDT"
MANUAL_SELL_BLOCKED_MARKET_CLOSED: Final[str] = "MANUAL_SELL_BLOCKED_MARKET_CLOSED"
MANUAL_SELL_BLOCKED_NO_BROKER_QTY: Final[str] = "MANUAL_SELL_BLOCKED_NO_BROKER_QTY"
MANUAL_SELL_BLOCKED_PENDING_ORDER: Final[str] = "MANUAL_SELL_BLOCKED_PENDING_ORDER"
MANUAL_SELL_ORDER_REJECTED: Final[str] = "MANUAL_SELL_ORDER_REJECTED"
ORDER_ALREADY_PENDING: Final[str] = "ORDER_ALREADY_PENDING"
DEFERRED_EXIT_WAITING_ON_PENDING_ORDER: Final[str] = "DEFERRED_EXIT_WAITING_ON_PENDING_ORDER"
BUY_BLOCKED_PENDING_PROFIT_EXIT: Final[str] = "BUY_BLOCKED_PENDING_PROFIT_EXIT"
STOCK_EXIT_SPREAD_TOO_WIDE: Final[str] = "STOCK_EXIT_SPREAD_TOO_WIDE"
STOCK_EXIT_SKIPPED_MARKET_CLOSED: Final[str] = "STOCK_EXIT_SKIPPED_MARKET_CLOSED"
OVERSIZED_EXIT_BLOCKED: Final[str] = "OVERSIZED_EXIT_BLOCKED"
CRYPTO_DUST_POSITION: Final[str] = "CRYPTO_DUST_POSITION"
STALE_CRYPTO_DUST_LOCAL: Final[str] = "STALE_CRYPTO_DUST_LOCAL"
WORKER_CYCLE_SLOW: Final[str] = "WORKER_CYCLE_SLOW"
CYCLE_WAITING_MARKET_CLOSED: Final[str] = "CYCLE_WAITING_MARKET_CLOSED"
WORKER_CYCLE_WAIT: Final[str] = "WORKER_CYCLE_WAIT"
BUY_BLOCKED_POST_PROFIT_COOLDOWN: Final[str] = "BUY_BLOCKED_POST_PROFIT_COOLDOWN"
BUY_BLOCKED_CAPITAL_ALLOCATOR_RESERVE: Final[str] = "BUY_BLOCKED_CAPITAL_ALLOCATOR_RESERVE"
BUY_BLOCKED_DYNAMIC_PROFIT_RESERVE: Final[str] = "BUY_BLOCKED_DYNAMIC_PROFIT_RESERVE"
BUY_BLOCKED_CRYPTO_RESERVED_CASH: Final[str] = "BUY_BLOCKED_CRYPTO_RESERVED_CASH"
DEFERRED_EXIT_CLOSED_NO_POSITION: Final[str] = "DEFERRED_EXIT_CLOSED_NO_POSITION"
BUY_LIMITED_BY_DYNAMIC_REDEPLOY_BUDGET: Final[str] = "BUY_LIMITED_BY_DYNAMIC_REDEPLOY_BUDGET"

# --- Crypto push/pull (paper worker) -----------------------------------------
CRYPTO_PUSH_ALLOWED: Final[str] = "CRYPTO_PUSH_ALLOWED"
CRYPTO_PUSH_BLOCKED_LOW_BUYING_POWER: Final[str] = "CRYPTO_PUSH_BLOCKED_LOW_BUYING_POWER"
CRYPTO_PUSH_BLOCKED_ALREADY_HOLDING: Final[str] = "CRYPTO_PUSH_BLOCKED_ALREADY_HOLDING"
CRYPTO_PUSH_BLOCKED_COOLDOWN: Final[str] = "CRYPTO_PUSH_BLOCKED_COOLDOWN"
CRYPTO_PUSH_BLOCKED_MAX_POSITIONS: Final[str] = "CRYPTO_PUSH_BLOCKED_MAX_POSITIONS"
CRYPTO_PUSH_BLOCKED_SCORE: Final[str] = "CRYPTO_PUSH_BLOCKED_SCORE"
CRYPTO_PUSH_BLOCKED_PREFLIGHT: Final[str] = "CRYPTO_PUSH_BLOCKED_PREFLIGHT"
CRYPTO_POSITION_ALREADY_OPEN: Final[str] = "CRYPTO_POSITION_ALREADY_OPEN"
NO_ADDITIONAL_CRYPTO_ENTRY_AVAILABLE: Final[str] = "NO_ADDITIONAL_CRYPTO_ENTRY_AVAILABLE"
CRYPTO_PUSH_DISABLED: Final[str] = "CRYPTO_PUSH_DISABLED"

CRYPTO_PULL_TAKE_PROFIT: Final[str] = "CRYPTO_PULL_TAKE_PROFIT"
CRYPTO_PULL_TRAILING_STOP: Final[str] = "CRYPTO_PULL_TRAILING_STOP"
CRYPTO_PULL_STOP_LOSS: Final[str] = "CRYPTO_PULL_STOP_LOSS"
CRYPTO_PULL_MAX_HOLD: Final[str] = "CRYPTO_PULL_MAX_HOLD"
CRYPTO_PULL_SIGNAL_DROPPED: Final[str] = "CRYPTO_PULL_SIGNAL_DROPPED"
CRYPTO_PULL_BLOCKED_NO_BROKER_QTY: Final[str] = "CRYPTO_PULL_BLOCKED_NO_BROKER_QTY"

# --- Preflight reason codes --------------------------------------------------
PREFLIGHT_APPROVED: Final[str] = "PREFLIGHT_APPROVED"
PREFLIGHT_BLOCKED_SESSION: Final[str] = "PREFLIGHT_BLOCKED_SESSION"
PREFLIGHT_BLOCKED_SPREAD: Final[str] = "PREFLIGHT_BLOCKED_SPREAD"
PREFLIGHT_BLOCKED_OPEN_ORDER: Final[str] = "PREFLIGHT_BLOCKED_OPEN_ORDER"
PREFLIGHT_BLOCKED_BUYING_POWER: Final[str] = "PREFLIGHT_BLOCKED_BUYING_POWER"
PREFLIGHT_BLOCKED_PDT: Final[str] = "PREFLIGHT_BLOCKED_PDT"
PREFLIGHT_BLOCKED_CAPITAL_ALLOCATOR: Final[str] = "PREFLIGHT_BLOCKED_CAPITAL_ALLOCATOR"

# --- Dynamic capital allocator (planning / diagnostics) ----------------------
CAPITAL_ALLOCATOR_PLAN_BUILT: Final[str] = "CAPITAL_ALLOCATOR_PLAN_BUILT"
CAPITAL_BUCKETS_UPDATED: Final[str] = "CAPITAL_BUCKETS_UPDATED"
CRYPTO_PUSH_BLOCKED_NO_FREE_CAPITAL: Final[str] = "CRYPTO_PUSH_BLOCKED_NO_FREE_CAPITAL"
CRYPTO_PUSH_BLOCKED_SPREAD: Final[str] = "CRYPTO_PUSH_BLOCKED_SPREAD"
CRYPTO_PUSH_BLOCKED_NO_NON_MARGIN_BUYING_POWER: Final[str] = "CRYPTO_PUSH_BLOCKED_NO_NON_MARGIN_BUYING_POWER"
CRYPTO_PUSH_READY_EXECUTION_DISABLED: Final[str] = "CRYPTO_PUSH_READY_EXECUTION_DISABLED"
STOCK_TO_CRYPTO_ROTATION_CANDIDATE: Final[str] = "STOCK_TO_CRYPTO_ROTATION_CANDIDATE"
STOCK_TO_CRYPTO_ROTATION_BLOCKED_PDT: Final[str] = "STOCK_TO_CRYPTO_ROTATION_BLOCKED_PDT"
STOCK_TO_CRYPTO_ROTATION_BLOCKED_MARKET_SESSION: Final[str] = "STOCK_TO_CRYPTO_ROTATION_BLOCKED_MARKET_SESSION"
STOCK_TO_CRYPTO_ROTATION_BLOCKED_PENDING_ORDER: Final[str] = "STOCK_TO_CRYPTO_ROTATION_BLOCKED_PENDING_ORDER"
STOCK_TO_CRYPTO_ROTATION_READY_EXECUTION_DISABLED: Final[str] = "STOCK_TO_CRYPTO_ROTATION_READY_EXECUTION_DISABLED"
CRYPTO_TO_STOCK_ROTATION_CANDIDATE: Final[str] = "CRYPTO_TO_STOCK_ROTATION_CANDIDATE"
CRYPTO_TO_STOCK_ROTATION_READY_EXECUTION_DISABLED: Final[str] = "CRYPTO_TO_STOCK_ROTATION_READY_EXECUTION_DISABLED"
CAPITAL_ALLOCATOR_DATA_MISSING: Final[str] = "CAPITAL_ALLOCATOR_DATA_MISSING"
CRYPTO_QUOTES_MISSING: Final[str] = "CRYPTO_QUOTES_MISSING"
CRYPTO_METADATA_MISSING: Final[str] = "CRYPTO_METADATA_MISSING"

# --- After-hours rotation ---------------------------------------------------
AH_EXIT_CANDIDATE: Final[str] = "AH_EXIT_CANDIDATE"
AH_EXIT_BLOCKED_NOT_ENABLED: Final[str] = "AH_EXIT_BLOCKED_NOT_ENABLED"
AH_EXIT_BLOCKED_SESSION: Final[str] = "AH_EXIT_BLOCKED_SESSION"
AH_EXIT_BLOCKED_SPREAD: Final[str] = "AH_EXIT_BLOCKED_SPREAD"
AH_EXIT_BLOCKED_PDT: Final[str] = "AH_EXIT_BLOCKED_PDT"
AH_EXIT_BLOCKED_OPEN_ORDER: Final[str] = "AH_EXIT_BLOCKED_OPEN_ORDER"
AH_EXIT_BLOCKED_NO_BROKER_QTY: Final[str] = "AH_EXIT_BLOCKED_NO_BROKER_QTY"
AH_EXIT_BLOCKED_NOT_PROFITABLE: Final[str] = "AH_EXIT_BLOCKED_NOT_PROFITABLE"
AH_EXIT_BLOCKED_NOTIONAL_TOO_SMALL: Final[str] = "AH_EXIT_BLOCKED_NOTIONAL_TOO_SMALL"
AH_EXIT_BLOCKED_NO_CRYPTO_EDGE: Final[str] = "AH_EXIT_BLOCKED_NO_CRYPTO_EDGE"
AH_EXIT_OBSERVE_ONLY: Final[str] = "AH_EXIT_OBSERVE_ONLY"
AH_CRYPTO_CANDIDATE: Final[str] = "AH_CRYPTO_CANDIDATE"
AH_CRYPTO_BLOCKED_DISABLED: Final[str] = "AH_CRYPTO_BLOCKED_DISABLED"
AH_CRYPTO_BLOCKED_SPREAD: Final[str] = "AH_CRYPTO_BLOCKED_SPREAD"
AH_CRYPTO_BLOCKED_SCORE: Final[str] = "AH_CRYPTO_BLOCKED_SCORE"

# --- Crypto night session ---------------------------------------------------
BUY_BLOCKED_CRYPTO_NIGHT_RESERVE: Final[str] = "BUY_BLOCKED_CRYPTO_NIGHT_RESERVE"
STOCK_ORDER_BLOCKED_CRYPTO_ONLY_SESSION: Final[str] = "STOCK_ORDER_BLOCKED_CRYPTO_ONLY_SESSION"
CRYPTO_NIGHT_PUSH_BLOCKED_LOW_CASH: Final[str] = "CRYPTO_NIGHT_PUSH_BLOCKED_LOW_CASH"
CRYPTO_NIGHT_PUSH_BLOCKED_SPREAD: Final[str] = "CRYPTO_NIGHT_PUSH_BLOCKED_SPREAD"
CRYPTO_NIGHT_PUSH_BLOCKED_SCORE: Final[str] = "CRYPTO_NIGHT_PUSH_BLOCKED_SCORE"
CRYPTO_NIGHT_PUSH_BLOCKED_COOLDOWN: Final[str] = "CRYPTO_NIGHT_PUSH_BLOCKED_COOLDOWN"
CRYPTO_NIGHT_PUSH_BLOCKED_ALLOCATION_CAP: Final[str] = "CRYPTO_NIGHT_PUSH_BLOCKED_ALLOCATION_CAP"
CRYPTO_NIGHT_PUSH_BLOCKED_DISABLED: Final[str] = "CRYPTO_NIGHT_PUSH_BLOCKED_DISABLED"

# --- Mission / capital constitution / kill switch --------------------------------
BUY_BLOCKED_HARD_CASH_RESERVE: Final[str] = "BUY_BLOCKED_HARD_CASH_RESERVE"
BUY_BLOCKED_MAX_STOCK_ALLOCATION: Final[str] = "BUY_BLOCKED_MAX_STOCK_ALLOCATION"
BUY_BLOCKED_MAX_CRYPTO_ALLOCATION: Final[str] = "BUY_BLOCKED_MAX_CRYPTO_ALLOCATION"
BUY_BLOCKED_CAPITAL_CONSTITUTION: Final[str] = "BUY_BLOCKED_CAPITAL_CONSTITUTION"
BUY_BLOCKED_MIN_USEFUL_NOTIONAL: Final[str] = "BUY_BLOCKED_MIN_USEFUL_NOTIONAL"
CAPITAL_TRAP_DETECTED: Final[str] = "CAPITAL_TRAP_DETECTED"
BUY_BLOCKED_MISSION_MODE: Final[str] = "BUY_BLOCKED_MISSION_MODE"
BUY_BLOCKED_MAX_STOCK_POSITIONS: Final[str] = "BUY_BLOCKED_MAX_STOCK_POSITIONS"
BUY_BLOCKED_PORTFOLIO_CAPITAL_TRAPPED: Final[str] = "BUY_BLOCKED_PORTFOLIO_CAPITAL_TRAPPED"
BUY_BLOCKED_PDT_TRAPPED_POSITIONS: Final[str] = "BUY_BLOCKED_PDT_TRAPPED_POSITIONS"
BUY_BLOCKED_STOCK_SPREAD_TOO_WIDE: Final[str] = "BUY_BLOCKED_STOCK_SPREAD_TOO_WIDE"
BUY_BLOCKED_STOCK_QUOTE_MISSING: Final[str] = "BUY_BLOCKED_STOCK_QUOTE_MISSING"
BUY_BLOCKED_LOW_LIQUIDITY: Final[str] = "BUY_BLOCKED_LOW_LIQUIDITY"
BUY_BLOCKED_PENNY_SPREAD_RISK: Final[str] = "BUY_BLOCKED_PENNY_SPREAD_RISK"
BUY_BLOCKED_DAILY_ONLY_SIGNAL_FOR_QUICK_TRADE: Final[str] = "BUY_BLOCKED_DAILY_ONLY_SIGNAL_FOR_QUICK_TRADE"
SIGNAL_DATA_STALE: Final[str] = "SIGNAL_DATA_STALE"
SIGNAL_INTRADAY_CONFIRMATION_MISSING: Final[str] = "SIGNAL_INTRADAY_CONFIRMATION_MISSING"
KILL_SWITCH_EXIT_SUBMITTED: Final[str] = "KILL_SWITCH_EXIT_SUBMITTED"
KILL_SWITCH_EXIT_BLOCKED_MARKET_CLOSED: Final[str] = "KILL_SWITCH_EXIT_BLOCKED_MARKET_CLOSED"
KILL_SWITCH_EXIT_BLOCKED_NO_BROKER_QTY: Final[str] = "KILL_SWITCH_EXIT_BLOCKED_NO_BROKER_QTY"
KILL_SWITCH_EXIT_ERROR: Final[str] = "KILL_SWITCH_EXIT_ERROR"
KILL_SWITCH_EXIT_ONLY_MODE_ACTIVE: Final[str] = "KILL_SWITCH_EXIT_ONLY_MODE_ACTIVE"
STALE_PRICE_FALLBACK: Final[str] = "STALE_PRICE_FALLBACK"
EXIT_BLOCKED_STALE_MARK_PRICE: Final[str] = "EXIT_BLOCKED_STALE_MARK_PRICE"

# Back-compat aliases (same runtime strings — kept so older dashboards/tests keep working)
CRYPTO_BUY_BLOCKED_LOW_BUYING_POWER = CRYPTO_PUSH_BLOCKED_LOW_BUYING_POWER
CRYPTO_BUY_BLOCKED_ALREADY_HOLDING = CRYPTO_PUSH_BLOCKED_ALREADY_HOLDING
CRYPTO_BUY_BLOCKED_COOLDOWN = CRYPTO_PUSH_BLOCKED_COOLDOWN
CRYPTO_BUY_BLOCKED_MAX_POSITIONS = CRYPTO_PUSH_BLOCKED_MAX_POSITIONS
CRYPTO_BUY_BLOCKED_SCORE = CRYPTO_PUSH_BLOCKED_SCORE
CRYPTO_TAKE_PROFIT = CRYPTO_PULL_TAKE_PROFIT
CRYPTO_TRAILING_STOP = CRYPTO_PULL_TRAILING_STOP
CRYPTO_STOP_LOSS = CRYPTO_PULL_STOP_LOSS
CRYPTO_MAX_HOLD_TIME = CRYPTO_PULL_MAX_HOLD


ALL_CODES: Final[tuple[str, ...]] = (
    MARKET_CLOSED,
    KILL_SWITCH,
    NOTIONAL_TOO_SMALL,
    MAX_POSITIONS,
    MAX_SINGLE_ASSET,
    MAX_DEPLOYED,
    SPREAD_TOO_WIDE,
    NO_PRICE,
    NO_BROKER_QTY,
    PDT_PROTECTION,
    LOCAL_POSITION_STALE,
    BROKER_POSITION_UNTRACKED,
    SYMBOL_NOT_TRADEABLE,
    NOT_FRACTIONABLE,
    INSUFFICIENT_BUYING_POWER,
    STOCK_BUYS_DISABLED_INSUFFICIENT_BUYING_POWER,
    CRYPTO_BUYS_DISABLED_INSUFFICIENT_BUYING_POWER,
    CRYPTO_BUY_BLOCKED_POSITION_CAP_BELOW_MIN_NOTIONAL,
    BROKER_RECONCILE_ADJUST,
    BROKER_LOCAL_MISMATCH,
    EXIT_BLOCKED_MARKET_CLOSED,
    COOLDOWN,
    DAILY_LOSS_LIMIT,
    ALREADY_LONG,
    ALREADY_SHORT,
    SCALP_EDGE_TOO_SMALL,
    SCALP_SCORE_TOO_LOW,
    SCALP_NOT_ENABLED,
    PAPER_FILL,
    ALPACA_ORDER_SUBMITTED,
    ALPACA_ORDER_REJECTED,
    ALPACA_PAPER_ORDER_SUBMITTED,
    ALPACA_PAPER_ORDER_REJECTED,
    LIVE_ORDER_BLOCKED,
    SHADOW_LIVE_BLOCKED,
    STOP_LOSS,
    TAKE_PROFIT,
    TRAILING_STOP,
    MAX_HOLD,
    EMERGENCY_EXIT,
    PDT_DEFERRED_EXIT_CREATED,
    PDT_DEFERRED_EXIT_READY,
    PDT_DEFERRED_EXIT_SUBMITTED,
    PDT_DEFERRED_EXIT_BLOCKED_AGAIN,
    PDT_DEFERRED_EXIT_CANCELLED_NO_POSITION,
    PDT_DEFERRED_EXIT_CANCELLED_PROFIT_REVERSED,
    MANUAL_SELL_SUBMITTED,
    MANUAL_SELL_BLOCKED_PDT,
    MANUAL_SELL_BLOCKED_MARKET_CLOSED,
    MANUAL_SELL_BLOCKED_NO_BROKER_QTY,
    MANUAL_SELL_BLOCKED_PENDING_ORDER,
    MANUAL_SELL_ORDER_REJECTED,
    ORDER_ALREADY_PENDING,
    STOCK_EXIT_SKIPPED_MARKET_CLOSED,
    OVERSIZED_EXIT_BLOCKED,
    CRYPTO_DUST_POSITION,
    STALE_CRYPTO_DUST_LOCAL,
    WORKER_CYCLE_SLOW,
    CYCLE_WAITING_MARKET_CLOSED,
    WORKER_CYCLE_WAIT,
    CRYPTO_PUSH_ALLOWED,
    CRYPTO_PUSH_BLOCKED_LOW_BUYING_POWER,
    CRYPTO_PUSH_BLOCKED_ALREADY_HOLDING,
    CRYPTO_PUSH_BLOCKED_COOLDOWN,
    CRYPTO_PUSH_BLOCKED_MAX_POSITIONS,
    CRYPTO_PUSH_BLOCKED_SCORE,
    CRYPTO_PUSH_BLOCKED_PREFLIGHT,
    CRYPTO_POSITION_ALREADY_OPEN,
    NO_ADDITIONAL_CRYPTO_ENTRY_AVAILABLE,
    CRYPTO_PUSH_DISABLED,
    CRYPTO_PULL_TAKE_PROFIT,
    CRYPTO_PULL_TRAILING_STOP,
    CRYPTO_PULL_STOP_LOSS,
    CRYPTO_PULL_MAX_HOLD,
    CRYPTO_PULL_SIGNAL_DROPPED,
    CRYPTO_PULL_BLOCKED_NO_BROKER_QTY,
    PREFLIGHT_APPROVED,
    PREFLIGHT_BLOCKED_SESSION,
    PREFLIGHT_BLOCKED_SPREAD,
    PREFLIGHT_BLOCKED_OPEN_ORDER,
    PREFLIGHT_BLOCKED_BUYING_POWER,
    PREFLIGHT_BLOCKED_PDT,
    PREFLIGHT_BLOCKED_CAPITAL_ALLOCATOR,
    CAPITAL_ALLOCATOR_PLAN_BUILT,
    CAPITAL_BUCKETS_UPDATED,
    CRYPTO_PUSH_BLOCKED_NO_FREE_CAPITAL,
    CRYPTO_PUSH_BLOCKED_SPREAD,
    CRYPTO_PUSH_BLOCKED_NO_NON_MARGIN_BUYING_POWER,
    CRYPTO_PUSH_READY_EXECUTION_DISABLED,
    STOCK_TO_CRYPTO_ROTATION_CANDIDATE,
    STOCK_TO_CRYPTO_ROTATION_BLOCKED_PDT,
    STOCK_TO_CRYPTO_ROTATION_BLOCKED_MARKET_SESSION,
    STOCK_TO_CRYPTO_ROTATION_BLOCKED_PENDING_ORDER,
    STOCK_TO_CRYPTO_ROTATION_READY_EXECUTION_DISABLED,
    CRYPTO_TO_STOCK_ROTATION_CANDIDATE,
    CRYPTO_TO_STOCK_ROTATION_READY_EXECUTION_DISABLED,
    CAPITAL_ALLOCATOR_DATA_MISSING,
    DEFERRED_EXIT_CLOSED_NO_POSITION,
    AH_EXIT_CANDIDATE,
    AH_EXIT_BLOCKED_NOT_ENABLED,
    AH_EXIT_BLOCKED_SESSION,
    AH_EXIT_BLOCKED_SPREAD,
    AH_EXIT_BLOCKED_PDT,
    AH_EXIT_BLOCKED_OPEN_ORDER,
    AH_EXIT_BLOCKED_NO_BROKER_QTY,
    AH_EXIT_BLOCKED_NOT_PROFITABLE,
    AH_EXIT_BLOCKED_NOTIONAL_TOO_SMALL,
    AH_EXIT_BLOCKED_NO_CRYPTO_EDGE,
    AH_EXIT_OBSERVE_ONLY,
    AH_CRYPTO_CANDIDATE,
    AH_CRYPTO_BLOCKED_DISABLED,
    AH_CRYPTO_BLOCKED_SPREAD,
    AH_CRYPTO_BLOCKED_SCORE,
    BUY_BLOCKED_CRYPTO_NIGHT_RESERVE,
    STOCK_ORDER_BLOCKED_CRYPTO_ONLY_SESSION,
    CRYPTO_NIGHT_PUSH_BLOCKED_LOW_CASH,
    CRYPTO_NIGHT_PUSH_BLOCKED_SPREAD,
    CRYPTO_NIGHT_PUSH_BLOCKED_SCORE,
    CRYPTO_NIGHT_PUSH_BLOCKED_COOLDOWN,
    CRYPTO_NIGHT_PUSH_BLOCKED_ALLOCATION_CAP,
    CRYPTO_NIGHT_PUSH_BLOCKED_DISABLED,
    BUY_BLOCKED_HARD_CASH_RESERVE,
    BUY_BLOCKED_MAX_STOCK_ALLOCATION,
    BUY_BLOCKED_MAX_CRYPTO_ALLOCATION,
    BUY_BLOCKED_CAPITAL_CONSTITUTION,
    BUY_BLOCKED_MIN_USEFUL_NOTIONAL,
    CAPITAL_TRAP_DETECTED,
    BUY_BLOCKED_MISSION_MODE,
    BUY_BLOCKED_MAX_STOCK_POSITIONS,
    BUY_BLOCKED_PORTFOLIO_CAPITAL_TRAPPED,
    BUY_BLOCKED_PDT_TRAPPED_POSITIONS,
    BUY_BLOCKED_STOCK_SPREAD_TOO_WIDE,
    BUY_BLOCKED_STOCK_QUOTE_MISSING,
    BUY_BLOCKED_LOW_LIQUIDITY,
    BUY_BLOCKED_PENNY_SPREAD_RISK,
    BUY_BLOCKED_DAILY_ONLY_SIGNAL_FOR_QUICK_TRADE,
    SIGNAL_DATA_STALE,
    SIGNAL_INTRADAY_CONFIRMATION_MISSING,
    KILL_SWITCH_EXIT_SUBMITTED,
    KILL_SWITCH_EXIT_BLOCKED_MARKET_CLOSED,
    KILL_SWITCH_EXIT_BLOCKED_NO_BROKER_QTY,
    KILL_SWITCH_EXIT_ERROR,
    KILL_SWITCH_EXIT_ONLY_MODE_ACTIVE,
    STALE_PRICE_FALLBACK,
    EXIT_BLOCKED_STALE_MARK_PRICE,
)


def is_known(code: str | None) -> bool:
    return bool(code) and code in ALL_CODES


# Map legacy lowercase reasons used by ``main_worker`` ``_can_buy`` / ``_can_open_short_stock``
# to the new structured codes so dashboard counters can group them.
LEGACY_TO_REASON: Final[dict[str, str]] = {
    "kill_switch": KILL_SWITCH,
    "notional_too_small": NOTIONAL_TOO_SMALL,
    "market_closed": MARKET_CLOSED,
    "max_stock_positions": BUY_BLOCKED_MAX_STOCK_POSITIONS,
    "max_crypto_positions": MAX_POSITIONS,
    "single_asset_cap": MAX_SINGLE_ASSET,
    "portfolio_cap": MAX_DEPLOYED,
    "already_long": ALREADY_LONG,
    "already_short": ALREADY_SHORT,
    "broker_qty_zero": NO_BROKER_QTY,
    "mission_mode_block": BUY_BLOCKED_MISSION_MODE,
    "pdt_trapped_portfolio": BUY_BLOCKED_PDT_TRAPPED_POSITIONS,
    "overnight_risk_block": BUY_BLOCKED_PORTFOLIO_CAPITAL_TRAPPED,
}


def normalize_reason(code: str | None) -> str:
    """Return canonical reason code for ``code`` (legacy strings included)."""
    if not code:
        return ""
    if code in ALL_CODES:
        return code
    return LEGACY_TO_REASON.get(str(code).strip().lower(), str(code).strip().upper())
