"""Static asset metadata for quick classification and search."""

CRYPTO_TOP_SYMBOLS = {
    "BTC-USD": "Bitcoin",
    "ETH-USD": "Ethereum",
    "BNB-USD": "BNB",
    "XRP-USD": "Ripple",
    "ADA-USD": "Cardano",
    "SOL-USD": "Solana",
    "DOGE-USD": "Dogecoin",
    "MATIC-USD": "Polygon",
    "DOT-USD": "Polkadot",
    "LTC-USD": "Litecoin",
    "SHIB-USD": "Shiba Inu",
    "TRX-USD": "Tron",
    "AVAX-USD": "Avalanche",
    "UNI-USD": "Uniswap",
    "ATOM-USD": "Cosmos",
    "LINK-USD": "Chainlink",
    "ETC-USD": "Ethereum Classic",
    "XMR-USD": "Monero",
    "XLM-USD": "Stellar",
    "NEAR-USD": "Near Protocol",
    "APT-USD": "Aptos",
    "ARB-USD": "Arbitrum",
    "OP-USD": "Optimism",
    "HBAR-USD": "Hedera",
    "FIL-USD": "Filecoin",
    "ICP-USD": "Internet Computer",
    "GRT-USD": "The Graph",
    "AAVE-USD": "Aave",
    "EGLD-USD": "MultiversX",
    "SAND-USD": "The Sandbox",
    "MANA-USD": "Decentraland",
    "FTM-USD": "Fantom",
    "ALGO-USD": "Algorand",
    "VET-USD": "VeChain",
    "FLOW-USD": "Flow",
    "XTZ-USD": "Tezos",
    "CHZ-USD": "Chiliz",
    "EOS-USD": "EOS",
    "THETA-USD": "Theta",
    "AXS-USD": "Axie Infinity",
    "SUI-USD": "Sui",
    "RNDR-USD": "Render",
    "IMX-USD": "ImmutableX",
    "STX-USD": "Stacks",
    "DYDX-USD": "dYdX",
    "RUNE-USD": "THORChain",
    "KLAY-USD": "Klaytn",
    "QNT-USD": "Quant",
    "LDO-USD": "Lido DAO",
}
